# Generated by Django 4.2.3 on 2023-08-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('lest_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('bank_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurance')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
