# Generated by Django 4.2.3 on 2023-08-30 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_logs_client_id_alter_logs_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
